<?php echo $this->doctype(); ?>

<html lang="fr">
  <head>
    <meta charset='utf-8'>
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet('http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css') ?>
    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile('http://code.jquery.com/jquery-1.9.1.min.js')
                                  ->prependFile('http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js') ?>

</head>
  
<!--  
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>
  -->

  <body>

 
    <div class="container">

      <?php echo $this->content; ?>

      <hr>



    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
